version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_transferencia
    restart: always
    environment:
      MYSQL_DATABASE: transferencia_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: redis_transferencia
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mysql_data:
  redis_data:
